import { legalGameMoves, moveForKey, moveKey, type GameId, type GameMove, type GameMoveKey, type GameState, type GridMove } from '../game/catalog';
import type { SamokState, Seat } from '../game/samok'; import { omokForbiddenKind, type OmokState } from '../game/omok';
import { voteMarks } from '../game/team-vote';
import { Board } from './Board';
import { BOARD_GEOMETRIES, ForbiddenPoint, GridBoard, LastTurnMarker, Stone } from './BoardGrid';
export interface LastTurnView { game: GameId; moves: number; cells: GridMove[] }
export function nextLastTurnView(game: GameId, previous: { game: GameId; state: GameState } | null, current: GameState, prior: LastTurnView): LastTurnView { const empty = { game, moves: current.moves, cells: [] as GridMove[] }; if (!previous || previous.game !== game || current.moves === 0 || current.moves < previous.state.moves || current.moves > previous.state.moves + 1 || current.board.length !== previous.state.board.length || current.board[0]?.length !== previous.state.board[0]?.length) return empty; const cells = current.board.flatMap((row, r) => row.flatMap((cell, column) => cell && !previous.state.board[r]?.[column] ? [{ row: r, column }] : [])); if (!cells.length) return current.moves === previous.state.moves && prior.game === game && prior.moves === current.moves ? prior : empty; const continued = game === 'yukmok' && previous.state.turn !== current.turn && 'stonesLeft' in previous.state && previous.state.stonesLeft === 1 && prior.game === game && prior.moves === previous.state.moves; return { game, moves: current.moves, cells: continued ? [...prior.cells, ...cells] : cells }; }
export const stoneRoleSeat = (game: GameId, state: GameState, seat: Seat): Seat => (game === 'omok' || game === 'yukmok') && 'starter' in state ? seat === state.starter ? 1 : 2 : seat;
interface Props { game: GameId; state: GameState; disabled?: boolean; selfId?: string | null; seat?: Seat | null; rouletteMove?: GameMoveKey | null; preview?: GameMove | null; lastTurn?: readonly GridMove[]; onMove?(move: GameMove): void; onSelect?(move: GameMove): void }
export function BoardGame({ game, state, disabled = false, selfId = null, seat = null, rouletteMove = null, preview = null, lastTurn = [], onMove, onSelect }: Props) { const select = onSelect ?? onMove ?? (() => undefined);
  if (game === 'samok') return <Board state={state as SamokState} disabled={disabled} selfId={selfId} seat={seat} rouletteColumn={rouletteMove === null ? null : Number(rouletteMove)} previewColumn={typeof preview === 'number' ? preview : null} lastTurn={lastTurn} onDrop={select} />;
  const legal = new Set(legalGameMoves(game, state).map(moveKey)), diameter = game === 'omok' ? 22 : game === 'yukmok' ? 18 : 44;
  const marks = voteMarks(state, selfId), roulette = rouletteMove === null ? null : moveForKey(game, state, rouletteMove) as GridMove | null, previewCell = typeof preview === 'object' ? preview : null, last = new Set(lastTurn.map(moveKey));
  return <GridBoard geometry={BOARD_GEOMETRIES[game]} board={state.board} label={`${game} board`} disabled={disabled} cellPixels={diameter + 2} rouletteCell={roulette && 'row' in roulette ? roulette : null}
    isLegal={(row, column) => legal.has(`${row}:${column}`)} onSelect={(row, column) => select({ row, column })} selectionLabel={(row, column) => `${row + 1}행 ${column + 1}열에 놓기`}
    renderCell={(cell, row, column, cx, cy) => { const shown = cell || (previewCell?.row === row && previewCell.column === column ? state.turn : 0); return <g key={`${row}:${column}`} role="gridcell" class={cell ? '' : shown ? 'move-preview' : ''} aria-label={cell ? `${cell}번 돌` : shown ? '미리보기 돌' : '빈칸'}>{shown ? <Stone seat={stoneRoleSeat(game, state, shown as Seat)} cx={cx} cy={cy} radius={40} diameterPixels={diameter} patternId={`${game}-dither`} /> : null}</g>; }}
    overlay={(row, column, cx, cy) => { const forbidden = game === 'omok' ? omokForbiddenKind(state as OmokState, row, column) : null, mark = marks.get(`${row}:${column}`); return last.has(`${row}:${column}`) ? <LastTurnMarker cx={cx} cy={cy} /> : forbidden ? <ForbiddenPoint key={`forbidden-${row}:${column}`} kind={forbidden} cx={cx} cy={cy} /> : mark ? <g key={`vote-${row}:${column}`} class={`vote-marker ${mark.own && seat ? `own-vote player-${seat}` : ''}`} aria-label={`${mark.count}표`}><circle cx={cx} cy={cy} r="18" /><text x={cx} y={cy + 7} text-anchor="middle">{mark.count}</text></g> : null; }} patternId={`${game}-dither`} />;
}
